service: bancolombia
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        -  arn:aws:dynamodb:us-east-1:967164748838:table/Vehicles

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  createCar:
    handler: src/addCar.addCar
    events:
      - httpApi:
          path: /cars
          method: post
  getCars:
    handler: src/getAllCars.getCars
    events:
      - httpApi:
          path: /cars
          method: get
  getCar:
    handler: src/getCar.getCar
    events:
      - httpApi:
          path: /cars/{id}
          method: get
  updateCar:
    handler: src/updateCar.updateCar
    events:
      - httpApi:
          path: /cars/{id}
          method: put
  deleteCar:
    handler: src/deleteCar.deleteCar
    events:
      - httpApi:
          path: /cars/{id}
          method: delete
       
resources:
  Resources:
    Vehicles:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Vehicles
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
